




.build/mega2560/src/StrafeTest.cpp : src/StrafeTest.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/StrafeTest.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/StrafeTest.cpp
	@true

